### PR TITLE
Clean up README.md

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Fix a typo, update a link to HTTPS and lightly rephrase the first paragraph.

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
I also suspect there’s a bug in the continuation example:

```python
for portion in continued:
    try:
        if 'query' in portion:
            for page in portion['query']['pages']:
                pages.append(page['title'])
        else:
            print("Mediwiki returned empty result batch.")
    except APIError:
        raise ValueError(
            "MediaWiki returned an error:", str(APIError)
        )
```

If there is an API error, it wouldn’t be raised in the section guarded by the `try`, but elsewhere, right? (cc @yurkobb)

**Comment by halfak** [comment]
Looks good to me.

**Comment by halfak** [comment]
Thanks for the cleanup!

**Comment by lucaswerkmeister** [comment]
Thanks for merging!

**Pull request merged**
